[package]
description = "A Rust-centric companion tool to Buck for usage in IDEs."
edition = "2021"
license = { workspace = true }
name = "rust-project"
readme = "README.md"
repository = { workspace = true }
version = "0.0.0"

[dependencies]
anyhow = { workspace = true }
clap = { workspace = true }
crossbeam = { workspace = true }
dunce = { workspace = true }
lsp-server = { workspace = true }
lsp-types = { workspace = true }
rustc-hash = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
