omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = 'Unresolved build script at vendor/zstd-safe-5.0.2+zstd.1.5.2/build.rs. Dependencies:'

[extra_mapped_srcs]

[platform_fixup]
