[package]
name = "buck2_test_proto"

edition = "2024"
license = { workspace = true }
repository = { workspace = true }
version = "0.1.0"

[dependencies]
buck2_data = { workspace = true }
buck2_host_sharing_proto = { workspace = true }
prost = { workspace = true }
prost-types = { workspace = true }
tonic = { workspace = true }

[build-dependencies]
buck2_protoc_dev = { workspace = true }
