omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/libsqlite3-sys-0.25.1/build.rs. Dependencies:
    cc-1.0.73
    pkg-config-0.3.25
    vcpkg-0.2.15'''

[extra_mapped_srcs]

[platform_fixup]
