omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/jemalloc-sys-0.3.2/build.rs. Dependencies:
    cc-1.0.73
    fs_extra-1.2.0'''

[extra_mapped_srcs]

[platform_fixup]
