[package]
edition = "2024"
license = { workspace = true }
name = "buck2_downward_api"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
async-trait = { workspace = true }
buck2_error = { workspace = true }
tracing = { workspace = true }
