[package]
description = """
Library providing an `anyhow` inspired error type for buck2
"""
edition = "2021"
license = { workspace = true }
name = "buck2_error"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
derive_more = { workspace = true }
either = { workspace = true }
itertools = { workspace = true }
ref-cast = { workspace = true }
smallvec = { workspace = true }
thiserror = { workspace = true }

allocative = { workspace = true }
dupe = { workspace = true }

buck2_data = { workspace = true }
buck2_error_derive = { workspace = true }

starlark_syntax = { workspace = true }
