omit_targets = []
extra_srcs = []
src_referenced_dirs = []
rustc_flags = []
cfgs = []
features = []
omit_features = []
extra_deps = []
filter_deps = []
cargo_env = false

[env]

[[buildscript]]
[buildscript.build]

[[buildscript]]
unresolved = '''
Unresolved build script at vendor/sys-info-0.8.0/build.rs. Dependencies:
    cc-1.0.73'''

[extra_mapped_srcs]

[platform_fixup]
