[package]
description = """
This crate defines the implementation logic for validation functionality.
"""
edition = "2021"
license = { workspace = true }
name = "buck2_validation"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
dice = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }

buck2_build_api = { workspace = true }
buck2_error = { workspace = true }
buck2_node = { workspace = true }
