[package]
authors = ["Meta"]
description = "Interface for build signals"
edition = "2021"
license = { workspace = true }
name = "buck2_build_signals"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
allocative = { workspace = true }
anyhow = { workspace = true }
async-trait = { workspace = true }
buck2_core = { workspace = true }
buck2_events = { workspace = true }
derive_more = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
