[package]
description = ""
edition = "2021"
license = { workspace = true }
name = "buck2"
repository = { workspace = true }
version = "0.1.0"

[dependencies]
anyhow = { workspace = true }
async-trait = { workspace = true }
backtrace = { workspace = true }
blake3 = { workspace = true }
clap = { workspace = true }
futures = { workspace = true }
hex = { workspace = true }
libc = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
termimad = { workspace = true }
tokio = { workspace = true }
tokio-stream = { workspace = true }
tracing = { workspace = true }

allocative = { workspace = true }
dice = { workspace = true }
dupe = { workspace = true }
fbinit = { workspace = true }
gazebo = { workspace = true }
host_sharing = { workspace = true }

buck2_action_impl = { workspace = true }
buck2_analysis = { workspace = true }
buck2_anon_target = { workspace = true }
buck2_audit = { workspace = true }
buck2_audit_server = { workspace = true }
buck2_build_api = { workspace = true }
buck2_build_info = { workspace = true }
buck2_build_signals = { workspace = true }
buck2_build_signals_impl = { workspace = true }
buck2_bxl = { workspace = true }
buck2_cfg_constructor = { workspace = true }
buck2_cli_proto = { workspace = true }
buck2_client = { workspace = true }
buck2_client_ctx = { workspace = true }
buck2_cmd_docs_server = { workspace = true }
buck2_common = { workspace = true }
buck2_configured = { workspace = true }
buck2_core = { workspace = true }
buck2_data = { workspace = true }
buck2_error = { workspace = true }
buck2_event_log = { workspace = true }
buck2_event_observer = { workspace = true }
buck2_events = { workspace = true }
buck2_external_cells = { workspace = true }
buck2_interpreter_for_build = { workspace = true }
buck2_query = { workspace = true }
buck2_query_impls = { workspace = true }
buck2_server = { workspace = true }
buck2_server_commands = { workspace = true }
buck2_server_ctx = { workspace = true }
buck2_starlark = { workspace = true }
buck2_starlark_server = { workspace = true }
buck2_test = { workspace = true }
buck2_test_runner = { workspace = true }
buck2_transition = { workspace = true }
buck2_util = { workspace = true }
buck2_validation = { workspace = true }
buck2_wrapper_common = { workspace = true }

[target.'cfg(any(target_os = "linux", target_os = "macos"))'.dependencies]
jemallocator = { workspace = true }

[target.'cfg(unix)'.dependencies]
dirs = { workspace = true }
nix = { workspace = true }

buck2_forkserver = { workspace = true }

[target.'cfg(windows)'.dependencies]
libc = { workspace = true }
winapi = { workspace = true }

[[bin]]
name = "buck2"
path = "bin/buck2.rs"
